### ISSUE TITLE
getting error when run "./waf"

### ISSUE THREAD

**Issue by zxy110** [arthurgervais/Bitcoin-Simulator#12]
Hello,
When I run "./waf" as I install the bitcoin simulator, I got the error `source ns3 header file helper/three-gpp-http-helper.hmodel/bitcoin.h not found` . 
That makes me confused, could you please help me?
Thanks !

**Comment by zxy110** [comment]
Hello,
I've solve the problem by moving the configure of `ns-allinone-3.xx/ns-3.xx/src/applications/wscript/headers.source` in front of previous configure.

**Comment by auqu** [comment]
hello, 
I have the same problem, cloud you please explain how did you solve it? I am confused..

**Comment by auqu** [comment]
Hi ...
I got it , we forgot a comma (,) after ==> 'helper/three-gpp-http-helper.h'**,**  and before ==>'model/bitcoin.h', 
 when we added that code line into headers.source

best regards
