### ISSUE TITLE
Error ("Can't use distributed simulator without MPI compiled in") occurs when use commands of tutorial

### ISSUE THREAD

**Issue by xlmabc** [arthurgervais/Bitcoin-Simulator#2]
Hello,

when I use command "./waf --run "bitcoin-test --noBlocks=100 --nodes=6000" in [tutorial]( http://arthurgervais.github.io/Bitcoin-Simulator/use_it.html) to run the simple Bitcoin simulation, an error occurs and the program terminates as shown below:
msg="Can't use distributed simulator without MPI compiled in", file=../../scratch/bitcoin-test.cc, line=559
terminate called without an active exception

I have already installed openmpi and other dependencies, and just run program without MPI acceleration, but I don't know why this MPI-related problems happen, could you help me?

Thanks a lot!

**Comment by xlmabc** [comment]
Problem solved!

I found any dependencies missed when use source code installation for OpenMPI. Instead, use apt-get install to ensure enable NS-3 to support MPI:

```
sudo apt-get install openmpi-bin openmpi-common openmpi-doc libopenmpi-dev
```

Then the program runs normally.

**Comment by arthurgervais** [comment]
Great, thanks 👍

**Comment by lamnd09** [comment]
Thanks

**Comment by charlatane** [comment]
@xlmabc I tried using your approach but it doesn't work for me

**Comment by charlatane** [comment]
I had to do the installation process all over again and it worked
